# Generated by Django 3.2.3 on 2021-05-15 12:37

import coupon.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('coupon_type', models.CharField(choices=[('Credit', 'Credit'), ('Percentage', 'Percentage')], default=coupon.models.CouponType['PERCENTAGE'], max_length=63)),
                ('credit_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('one_time', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
