# Generated by Django 3.2.3 on 2021-05-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('title_de', models.TextField(null=True)),
                ('title_en', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsletter')),
                ('text', models.TextField()),
                ('title_done', models.TextField(help_text='Title for the popup after subscribing')),
                ('title_done_de', models.TextField(help_text='Title for the popup after subscribing', null=True)),
                ('title_done_en', models.TextField(help_text='Title for the popup after subscribing', null=True)),
                ('text_done', models.TextField(help_text='Text for the popup after subscribing')),
                ('text_done_de', models.TextField(help_text='Text for the popup after subscribing', null=True)),
                ('text_done_en', models.TextField(help_text='Text for the popup after subscribing', null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter campaign',
                'verbose_name_plural': 'Newsletter campaigns',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'ordering': ('created', 'email'),
            },
        ),
    ]
