# Generated by Django 3.2.4 on 2021-06-26 23:47

from django.conf import settings
from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_alter_authorsorderable_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(limit_choices_to={'is_staff': True}, related_name='blog_authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
