# Generated by Django 3.2.4 on 2021-07-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_articlepage_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesorderable',
            name='category_ptr',
        ),
        migrations.RemoveField(
            model_name='categoriesorderable',
            name='page',
        ),
        migrations.DeleteModel(
            name='AuthorsOrderable',
        ),
        migrations.DeleteModel(
            name='CategoriesOrderable',
        ),
    ]
