# Generated by Django 3.2.3 on 2021-05-15 12:37

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('text_color', models.CharField(max_length=127)),
                ('background_color', models.CharField(max_length=127)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('order', models.IntegerField()),
                ('font_awesome_class', models.CharField(blank=True, help_text='fas fa-list; check: https://fontawesome.com/', max_length=63, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TextPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.core.fields.RichTextField()),
                ('body_de', wagtail.core.fields.RichTextField(null=True)),
                ('body_en', wagtail.core.fields.RichTextField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_with_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='Text', required=True))])), ('image_left_text_right', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='Text', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image', required=True))])), ('image_right_text_left', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='Text', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='image', required=True))])), ('hero_block_text_left', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image', required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Text', required=True)), ('button_text', wagtail.core.blocks.CharBlock(help_text='Button text', required=False)), ('button_url', wagtail.core.blocks.CharBlock(help_text='Button url', required=False))])), ('hero_block_text_right', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image', required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Text', required=True)), ('button_text', wagtail.core.blocks.CharBlock(help_text='Button text', required=False)), ('button_url', wagtail.core.blocks.CharBlock(help_text='Button url', required=False))])), ('product', wagtail.core.blocks.StructBlock([('product', wagtail.core.blocks.PageChooserBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_de',
            field=wagtail.core.fields.StreamField([('title_with_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='Text', required=True))])), ('image_left_text_right', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='Text', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image', required=True))])), ('image_right_text_left', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='Text', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='image', required=True))])), ('hero_block_text_left', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image', required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Text', required=True)), ('button_text', wagtail.core.blocks.CharBlock(help_text='Button text', required=False)), ('button_url', wagtail.core.blocks.CharBlock(help_text='Button url', required=False))])), ('hero_block_text_right', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image', required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Text', required=True)), ('button_text', wagtail.core.blocks.CharBlock(help_text='Button text', required=False)), ('button_url', wagtail.core.blocks.CharBlock(help_text='Button url', required=False))])), ('product', wagtail.core.blocks.StructBlock([('product', wagtail.core.blocks.PageChooserBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content_en',
            field=wagtail.core.fields.StreamField([('title_with_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='Text', required=True))])), ('image_left_text_right', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='Text', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image', required=True))])), ('image_right_text_left', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='Text', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='image', required=True))])), ('hero_block_text_left', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image', required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Text', required=True)), ('button_text', wagtail.core.blocks.CharBlock(help_text='Button text', required=False)), ('button_url', wagtail.core.blocks.CharBlock(help_text='Button url', required=False))])), ('hero_block_text_right', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image', required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='Title', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Text', required=True)), ('button_text', wagtail.core.blocks.CharBlock(help_text='Button text', required=False)), ('button_url', wagtail.core.blocks.CharBlock(help_text='Button url', required=False))])), ('product', wagtail.core.blocks.StructBlock([('product', wagtail.core.blocks.PageChooserBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=127, null=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=127)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('link_url', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField()),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('font_awesome_class', models.CharField(blank=True, help_text='fas fa-list; check: https://fontawesome.com/', max_length=63, null=True)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='home.menu')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('link_url', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField()),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('font_awesome_class', models.CharField(blank=True, help_text='fas fa-list; check: https://fontawesome.com/', max_length=63, null=True)),
                ('include_in_mobile_menu', models.BooleanField(default=False)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
