# Generated by Django 3.2.3 on 2021-05-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210515_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='footeritem',
            name='title_de',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='footeritem',
            name='title_en',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='informationbar',
            name='text_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='informationbar',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_de',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_en',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_de',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title_en',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
