# Generated by Django 3.2.3 on 2021-06-16 15:21

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210616_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='footeritem',
            name='footer',
            field=modelcluster.fields.ParentalKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='footer_item', to='home.footer'),
            preserve_default=False,
        ),
    ]
