# Generated by Django 3.2.3 on 2021-06-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_footeritem_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footeritem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='footeritem',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='footeritem',
            name='title_en',
        ),
    ]
