# Generated by Django 3.2.3 on 2021-05-16 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210515_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='weight',
            field=models.IntegerField(default=0, help_text='Use the smallest unit possible (e.g. gram)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
