# Generated by Django 3.2.3 on 2021-06-15 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210606_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.productcategory'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='size_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.sizecategory'),
        ),
    ]
