# Generated by Django 3.2.3 on 2021-05-15 12:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=61, verbose_name='first name')),
                ('last_name', models.CharField(max_length=61, verbose_name='last name')),
                ('company', models.CharField(blank=True, max_length=126, null=True, verbose_name='company')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('address', models.CharField(max_length=126, verbose_name='address')),
                ('address2', models.CharField(blank=True, max_length=126, null=True, verbose_name='address2')),
                ('postal_code', models.CharField(max_length=15, verbose_name='postal code')),
                ('country', models.CharField(max_length=255, verbose_name='country')),
                ('city', models.CharField(max_length=125, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=125, null=True, verbose_name='state')),
                ('telephone', models.CharField(blank=True, max_length=125, null=True, verbose_name='telephone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_2', models.CharField(max_length=2, unique=True)),
                ('iso_3', models.CharField(max_length=3, unique=True)),
                ('country', models.CharField(max_length=255)),
                ('country_de', models.CharField(max_length=255, null=True)),
                ('country_en', models.CharField(max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ('order', 'country'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('first_name', models.CharField(max_length=63, verbose_name='first name')),
                ('last_name', models.CharField(max_length=63, verbose_name='last name')),
                ('company', models.CharField(blank=True, max_length=127, null=True, verbose_name='company')),
                ('address', models.CharField(max_length=127, verbose_name='address')),
                ('address2', models.CharField(blank=True, max_length=127, null=True, verbose_name='address2')),
                ('postal_code', models.CharField(max_length=15, verbose_name='postal code')),
                ('country', models.CharField(max_length=255, verbose_name='country')),
                ('city', models.CharField(max_length=127, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=127, null=True, verbose_name='state')),
                ('telephone', models.CharField(blank=True, max_length=127, null=True, verbose_name='telephone')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('url', models.CharField(max_length=31, unique=True)),
                ('stripe_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('tracking_number_link', models.CharField(blank=True, max_length=510, null=True)),
                ('paid', models.BooleanField()),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Canceled', 'Canceled')], default=order.models.OrderStatus['PROCESSING'], max_length=63)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PaypalVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('intent', models.CharField(max_length=255)),
                ('links', models.TextField()),
                ('currency', models.CharField(max_length=255)),
                ('gross_amount', models.CharField(max_length=255)),
                ('custom_order_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Paypal verification',
                'verbose_name_plural': 'Paypal verifications',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Name')),
                ('name_de', models.CharField(max_length=127, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=127, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=127, null=True, verbose_name='Description')),
                ('description_de', models.CharField(blank=True, max_length=127, null=True, verbose_name='Description')),
                ('description_en', models.CharField(blank=True, max_length=127, null=True, verbose_name='Description')),
                ('min_weight', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum weight')),
                ('max_weight', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum weight')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_de', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('iso', models.CharField(max_length=8)),
                ('state_code', models.CharField(max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_state', to='order.country')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('value', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('value_de', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('value_en', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size', models.CharField(max_length=63)),
                ('order', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
            ],
            options={
                'ordering': ('-order',),
            },
        ),
    ]
