# Generated by Django 3.2.3 on 2021-05-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('order', 'country', 'iso_2'), 'verbose_name_plural': 'Countries'},
        ),
    ]
