# Generated by Django 3.2.3 on 2021-05-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
