# Generated by Django 3.2.3 on 2021-05-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210516_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paypal_verification',
        ),
        migrations.DeleteModel(
            name='PaypalVerification',
        ),
    ]
