# Generated by Django 3.2.3 on 2021-06-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210516_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unique_paid_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
