# Generated by Django 3.2.3 on 2021-06-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210609_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('order', 'name', 'iso_2'), 'verbose_name_plural': 'Countries'},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_de',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country_en',
            new_name='name_en',
        ),
    ]
