# Generated by Django 3.2.3 on 2021-05-15 12:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinwheelParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WinwheelSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('txt_display_text', models.CharField(help_text='Text on the wheel', max_length=31)),
                ('txt_result_title', models.CharField(help_text='Title after the spin', max_length=255)),
                ('txt_result_title_de', models.CharField(help_text='Title after the spin', max_length=255, null=True)),
                ('txt_result_title_en', models.CharField(help_text='Title after the spin', max_length=255, null=True)),
                ('txt_result_text', models.CharField(help_text='Text after the win', max_length=255)),
                ('txt_result_text_de', models.CharField(help_text='Text after the win', max_length=255, null=True)),
                ('txt_result_text_en', models.CharField(help_text='Text after the win', max_length=255, null=True)),
                ('txt_color', models.CharField(help_text='Text color on the wheel (#ffffff)', max_length=255)),
                ('txt_background_color', models.CharField(help_text='Background color', max_length=255)),
                ('percentage_of_winning', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winwheel_section', to='coupon.coupon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
