# Generated by Django 3.2.3 on 2021-05-15 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winwheel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winwheelsection',
            name='percentage_of_winning',
            field=models.IntegerField(help_text='Percentage of it landing on this section (in percent, full number)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='winwheelsection',
            name='txt_background_color',
            field=models.CharField(help_text='Background color (#ffffff)', max_length=255),
        ),
    ]
